version: '2'
services:
    web:
        build: .
        ports:
          - "9090:9090"
          - "9229:9229"
        volumes:
          - ./bundles:/usr/src/app/bundles
          - ./cfg:/usr/src/app/cfg
          - db-data:/usr/src/app/db

volumes:
  db-data:
