version: '2'
services:
    web:
        build: .
        ports:
          - "9090:9090"
        volumes:
          - ./bundles:/usr/src/app/bundles
          - ./cfg:/usr/src/app/cfg
          - ./db:/usr/src/app/db